sudo: required
language: go

go:
  - 1.8

install:
  - go get github.com/mattn/goveralls
  - go get golang.org/x/tools/cmd/cover
  - go get github.com/golang/lint/golint
  - go get github.com/pierrre/gotestcover
  - go get -t ./...

services:
  - docker

script:
  - go vet -x ./compose
  - golint ./compose
  - gotestcover -coverprofile="cover.out" -race -covermode="count" ./compose
  - goveralls -coverprofile="cover.out"

after_failure:
  - docker logs ms
  - docker logs pg
